import styles from '../../styles/Table.module.css'
import DataTable, { createTheme } from 'react-data-table-component'
import DotMenuIcon from '../Icons/DotMenuIcon'

const data = [
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '123456789',
    nombre: 'IAN ROSALES',
    dni: '96083523',
    localidad: 'BARRACAS',
    provincia: 'CABA',
    cp: '1272',
    tipoDeEnvio: 'DOMICILIO',
    transporte: 'CORREO ARGENTINO',
    creado: '19/7/2021 19:24 hs',
    nroGuia: 'ASD2165SDF153ADS654HJ',
    estado: 'ENVIADO',
  },
  {
    usuario: 'GABRIEL RUEJAS',
    nroPedido: '322165487',
    nombre: 'NILKARBIS QUIROZ',
    dni: '96092355',
    localidad: 'FLORES',
    provincia: 'CABA',
    cp: '6712',
    tipoDeEnvio: 'SUCURSAL',
    transporte: 'MOTO EXPRESS',
    creado: '16/7/2021 10:52 hs',
    nroGuia: '-',
    estado: 'EN DEPOSITO',
  },
]
const columns = [
  { name: 'Nro. de Pedido', selector: 'nroPedido', sortable: true },
  { name: 'Nombre', selector: 'nombre', sortable: true },
  { name: 'Localidad', selector: 'localidad', sortable: true },
  { name: 'CP', selector: 'cp', sortable: true },
  { name: 'Tipo De Envio', selector: 'tipoDeEnvio', sortable: true },
  { name: 'Transporte', selector: 'transporte', sortable: true },
  { name: 'Creado', selector: 'creado', sortable: true },
  { name: 'Nro. de Guia', selector: 'nroGuia', sortable: true },
  { name: 'Estado', selector: 'estado', sortable: true },
  { name: 'Opciones', cell: (row) => <DotMenuIcon width='18' />, allowOverflow: true, button: true, style: { cursor: 'pointer' } },
]

const pagination = {
  rowsPerPageText: 'Filas por página',
  rangeSeparatorText: 'de',
  selectAllRowsItem: true,
  selectAllRowsItemText: 'Todos',
}

createTheme('solarized', {
  text: {
    primary: 'var(--color-black-custom-80)',
    secondary: 'var(--color-black-custom-60)',
  },
  background: {
    default: 'transparent',
    hover: 'red',
  },
  context: {
    background: 'transparent',
    text: 'var(--color-black-custom-80)',
  },
  divider: {
    default: 'var(--color-black-custom-05)',
  },
  action: {
    button: 'var(--color-black-custom-80)',
    hover: 'var(--color-black-custom-80)',
    disabled: 'var(--color-black-custom-80)',
  },
})

const customStyles = {
  rows: {
    style: {
      minHeight: '72px',
    },
    highlightOnHoverStyle: {
      backgroundColor: 'var(--color-primary-05)',
    },
  },
  headCells: {
    style: {
      paddingLeft: '8px',
      paddingRight: '8px',
    },
  },
  cells: {
    style: {
      paddingLeft: '8px',
      paddingRight: '8px',
    },
  },
}

export default function MyOrdersTable() {
  return (
    <div className={styles.container}>
      <DataTable
        columns={columns}
        customStyles={customStyles}
        data={data}
        highlightOnHover
        pagination
        paginationComponentOptions={pagination}
        paginationPerPage={25}
        paginationRowsPerPageOptions={[10, 25, 50]}
        responsive
        theme='solarized'
      />
    </div>
  )
}
