// Create new order
POST http://localhost:3000/api/orders/post
content-type: application/json

{
    "orderId": "96083523",
    "userId": "63714be13ba2ec1bca1c37c0",
    "email": "Ianrosales@gmail.com",
    "name": "juancito"
}

###

// Edit order by id
POST http://localhost:3000/api/orders/put/63208cbda25c01bb3661b2e0
content-type: application/json

{
    "displayName": "Ian Rosales",
    "email": "ianrosales@gmail.com",
    "password": "31555117"
}

### 

// Get all orders
GET http://localhost:3000/api/orders/get

###

// Get order by id
GET http://localhost:3000/api/orders/get/6371340440f80f5442fad687

###

// Delete order by id
DELETE http://localhost:3000/api/orders/delete/6320d3e09c1322f246cf4f76