import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header'
import styles from '../styles/index.module.css'

import Image from 'next/image'
import FacebookIcon from '../components/Icons/FacebookIcon'
import InstagramIcon from '../components/Icons/InstagramIcon'
import YoutubeIcon from '../components/Icons/YoutubeIcon'
import WhatsappIcon from '../components/Icons/WhatsappIcon'

export default function Home() {
  return (
    <>
      <Head>
        <title>SM Logística</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <div className={styles.header}>
          <div className={styles.contentSmall}>
            <div className={styles.textHeader}>
              <h2>
                BIENVENIDO! <br /> <span>SM LOGISTICA</span>
              </h2>
              <p>
                Diseñamos soluciones logísticas <br /> a la medida de su negocio.
              </p>
              <div className={styles.buttons}>
                <Link href={'/docs/admin'}>
                  <a className={styles.buttonLight}>SERVICIOS</a>
                </Link>
                <Link href={'/clients-area/admin'}>
                  <a className={styles.button}>AREA CLIENTES</a>
                </Link>
              </div>
            </div>
          </div>
          <a className={styles.arrowDownButton} href="#main">
            <i className={styles.arrowDown}></i>
          </a>
          <div className={styles.content}>
            <Image
              className={styles.img}
              src={'/20945983.jpg'}
              width="900px"
              height="600px"
              alt="Logistica"
              placeholder="blur"
              blurDataURL="/20945983.jpg"
            />
          </div>
        </div>
        <main className={styles.main} id="main">
          <section>
            <div className={styles.content}>
              <Image
                className={styles.img}
                src={'/20945391.jpg'}
                width="600px"
                height="600px"
                alt="Logistica"
                placeholder="blur"
                blurDataURL="/20945391.jpg"
              />
            </div>
            <div className={styles.content}>
              <div className={styles.textHeader}>
                <h2>
                  BIENVENIDO! <span>SM LOGISTICA</span>
                </h2>
                <p>
                  Diseñamos soluciones logísticas <br /> a la medida de su negocio.
                </p>
                <div className={styles.buttons}>
                  <Link href={'/docs/admin'}>
                    <a className={styles.buttonLight}>SERVICIOS</a>
                  </Link>
                  <Link href={'/clients-area/admin'}>
                    <a className={styles.button}>AREA CLIENTES</a>
                  </Link>
                </div>
              </div>
            </div>
          </section>
          <section>
            <div className={styles.content}>
              <div className={styles.textHeader}>
                <h2>
                  BIENVENIDO! <span>SM LOGISTICA</span>
                </h2>
                <p>
                  Diseñamos soluciones logísticas <br /> a la medida de su negocio.
                </p>
                <div className={styles.buttons}>
                  <Link href={'/docs/admin'}>
                    <a className={styles.buttonLight}>SERVICIOS</a>
                  </Link>
                  <Link href={'/clients-area/admin'}>
                    <a className={styles.button}>AREA CLIENTES</a>
                  </Link>
                </div>
              </div>
            </div>
            <div className={styles.content}>
              <Image
                className={styles.img}
                src={'/20943716.jpg'}
                width="600px"
                height="600px"
                alt="Logistica"
                placeholder="blur"
                blurDataURL="/20943716.jpg"
              />
            </div>
          </section>
          <section>
            <div className={styles.content}>
              <Image
                className={styles.img}
                src={'/20945238.jpg'}
                width="600px"
                height="600px"
                alt="Logistica"
                placeholder="blur"
                blurDataURL="/20945238.jpg"
              />
            </div>
            <div className={styles.content}>
              <div className={styles.textHeader}>
                <h2>
                  BIENVENIDO! <span>SM LOGISTICA</span>
                </h2>
                <p>
                  Diseñamos soluciones logísticas <br /> a la medida de su negocio.
                </p>
                <div className={styles.buttons}>
                  <Link href={'/docs/admin'}>
                    <a className={styles.buttonLight}>SERVICIOS</a>
                  </Link>
                  <Link href={'/clients-area/admin'}>
                    <a className={styles.button}>AREA CLIENTES</a>
                  </Link>
                </div>
              </div>
            </div>
          </section>
        </main>
        <ul className={styles.socialContainer}>
          <li>
            <a href="#">
              <FacebookIcon width="18" />
            </a>
          </li>
          <li>
            <a href="#">
              <InstagramIcon width="18" />
            </a>
          </li>
          <li>
            <a href="#">
              <YoutubeIcon width="18" />
            </a>
          </li>
          <li>
            <a href="#">
              <WhatsappIcon width="18" />
            </a>
          </li>
          <div className={styles.hr}></div>
        </ul>
        <div className={styles.decorationCircle}></div>
      </div>
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <div className={styles.content}>
            <h2>ACERCA DE</h2>
            <ul>
              <li>SM Logistica</li>
              <li>Términos y condiciones</li>
              <li>Política de privacidad</li>
            </ul>
            <h2>SERVICIOS</h2>
            <ul>
              <li>Promociones</li>
              <li>Tendencias</li>
              <li>Envíos</li>
            </ul>
          </div>
          <div className={styles.content}>
            <h2>AYUDA</h2>
            <ul>
              <li>¿Cómo enviar?</li>
              <li>Qué es consolidado</li>
              <li>Dónde veo mi número de guía</li>
              <li>Preguntas generales</li>
              <li>E-comerces</li>
              <li>Pagos</li>
              <li>Mi cuenta</li>
            </ul>
          </div>
        </div>
        <div className={styles.content}></div>
        <div className={styles.copyright}>&copy; 2022 SM Logística</div>
      </footer>
    </>
  )
}
