import styles from './index.module.css'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useSelector, useDispatch } from 'react-redux'
import { incremented, decremented } from '../store/features/users/userSlice'

import Button from '../components/Button'
import Header from '../components/Header'

import FacebookIcon from '../components/Icons/FacebookIcon'
import InstagramIcon from '../components/Icons/InstagramIcon'
import YoutubeIcon from '../components/Icons/YoutubeIcon'
import WhatsappIcon from '../components/Icons/WhatsappIcon'
import QuoteLeft from '../components/Icons/QuoteLeft'
import LogoCorreoArgentinoIcon from '../components/Icons/LogoCorreoArgentinoIcon'
import LogoOcaIcon from '../components/Icons/LogoOcaIcon'
import BoxOverHandIcon from '../components/Icons/BoxOverHandIcon'
import SendBoxIcon from '../components/Icons/SendBoxIcon'
import TicketBoxIcon from '../components/Icons/TicketBoxIcon'
import ChartIcon from '../components/Icons/ChartIcon'
import LogoIcon from '../components/Icons/LogoIcon'
import HeadsetIcon from '../components/Icons/HeadsetIcon'
import ArrowRightToBracketIcon from '../components/Icons/ArrowRightToBracketIcon'

export default function Home() {
  const user = useSelector((state) => state.user)
  const dispatch = useDispatch()
  return (
    <>
      <Head>
        <title>SM Logística</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.header}>
        <div className={styles.container}>
          <div className={styles.content}>
            <div className={styles.textBox}>
              <h2 className={styles.subTitle}>
                <span>
                  EN <strong>{user}</strong>
                </span>
                Diseñamos soliciones logisticas a la medida de <strong>tus necesidades.</strong> <br />
                Expandemos tu negocio y hacemos crecer tus ventas <strong>facil y rapido.</strong> <br />
                Realizamos envios de forma masiva a <strong>todo el pais.</strong>
              </h2>
              <div className={styles.buttons}>
                <Button
                  onClick={() => {
                    dispatch(incremented())
                  }}
                  className="buttonPrimary"
                  light
                  color={'var(--color-white-100)'}
                >
                  SERVICIOS
                </Button>
                <Button
                  onClick={() => {
                    dispatch(decremented())
                  }}
                  className="buttonPrimary"
                  background={'var(--color-primary-80)'}
                >
                  AREA CLIENTES
                </Button>
              </div>
            </div>
            <div className={styles.imgContent}>
              <LogoIcon height={360} />
            </div>
          </div>
        </div>
      </div>
      <main className={styles.main} id="main">
        <section>
          <div className={styles.container}>
            <div className={styles.boxes}>
              <div className={styles.box}>
                <div className={styles.boxHeader}>
                  <div className={styles.boxIconContainer} style={{ width: '60%' }}>
                    <div className={styles.boxIcon}>
                      <SendBoxIcon width={36} />
                    </div>
                  </div>
                  <h3 className={styles.boxData}>
                    <small>Hemos Enviado</small>
                    96056
                    <small>Pedidos con Exito</small>
                  </h3>
                </div>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type
                </p>
              </div>
              <div className={styles.box}>
                <div className={styles.boxHeader}>
                  <div className={styles.boxIconContainer} style={{ width: '60%' }}>
                    <div className={styles.boxIcon}>
                      <BoxOverHandIcon width={36} />
                    </div>
                  </div>
                  <h3 className={styles.boxData}>
                    <small>Ahora Hasta</small>
                    60%
                    <small>En Envios</small>
                  </h3>
                </div>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type
                </p>
              </div>
              <div className={styles.box}>
                <div className={styles.boxHeader}>
                  <div className={styles.boxIconContainer} style={{ width: '60%' }}>
                    <div className={styles.boxIcon}>
                      <ChartIcon width={28} />
                    </div>
                  </div>
                  <h3 className={styles.boxData}>
                    <small>Aumenta Hasta</small>
                    40%
                    <small>Tus Ventas</small>
                  </h3>
                </div>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className={styles.container}>
            <div className={styles.content}>
              <div className={styles.textBox}>
                <h3 className={styles.subTitle}>
                  <strong>
                    Diseñamos soliciones logisticas a la medida de tus necesidades tu negocio y hacemos crecer tus venta sa la medida de tus
                    necesidades
                  </strong>
                </h3>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type
                  and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronim
                  Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
                <div className={styles.buttons}>
                  <Button href={'#'} className="buttonPrimary">
                    VER MAS
                  </Button>
                </div>
              </div>
              <div className={styles.imgContent}>
                <Image src={'/logistica01.jpg'} alt={'img'} width={'680'} height={'450'} />
              </div>
            </div>
          </div>
        </section>
        <section className={styles.wbg}>
          <div className={styles.container}>
            <h3 className={styles.sectionTitle}>
              <small>NUESTROS SERVICIOS</small>
              Detalles & Beneficios
            </h3>
            <div className={styles.boxes}>
              <div className={styles.notBox}>
                <QuoteLeft width={22} fill="#3d3ec3" />
                <p>
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text
                  ever since the 1500s.
                </p>
                <h3 className={styles.subTitle}>Nilkarbis Quiroz &middot; 2022</h3>
              </div>
              <div className={styles.box}>
                <div>
                  <div className={styles.boxIconContainer}>
                    <div className={styles.boxIcon}>
                      <ChartIcon width={28} />
                    </div>
                  </div>
                  <p>
                    <span>Lorem Ipsum</span> dummy text ever since the 1500s, when an printer took a galley.
                  </p>
                </div>
              </div>
              <div className={styles.box}>
                <div>
                  <div className={styles.boxIconContainer}>
                    <div className={styles.boxIcon}>
                      <TicketBoxIcon width={32} />
                    </div>
                  </div>
                  <p>
                    <span>Lorem Ipsum</span> dummy text ever since the 1500s, when an printer took a galley.
                  </p>
                </div>
              </div>
              <div className={styles.box}>
                <div>
                  <div className={styles.boxIconContainer}>
                    <div className={styles.boxIcon}>
                      <HeadsetIcon width={28} />
                    </div>
                  </div>
                  <p>
                    <span>Lorem Ipsum</span> dummy text ever since the 1500s, when an printer took a galley.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className={styles.container}>
            <h3 className={styles.sectionTitle}>
              <small>ESTADISTICAS DE ENVIOS</small>
              Información & Graficas
            </h3>
            <div className={styles.boxes}>
              <div className={styles.notBox}>
                <Image src={'/statistics02.jpeg'} alt={'img'} width={'400px'} height={'480px'} objectFit="cover" />
              </div>
              <div className={styles.notBox}>
                <Image src={'/statistics03.jpg'} alt={'img'} width={'400px'} height={'480px'} objectFit="cover" />
              </div>
              <div className={styles.notBox}>
                <Image src={'/statistics01.jpeg'} alt={'img'} width={'400px'} height={'480px'} objectFit="cover" />
              </div>
            </div>
          </div>
        </section>
        <section className={styles.dbg}>
          <div className={styles.container}>
            <h3 className={styles.sectionTitle}>
              <span>
                ¡Envia Con Nosotros Ya!{' '}
                <Button className={'buttonPrimary'}>
                  CREAR CUENTA <ArrowRightToBracketIcon width={16} />
                </Button>
              </span>
            </h3>
          </div>
        </section>
        <section>
          <div className={styles.container}>
            <h3 className={styles.sectionTitle}>EXPRESOS ADHERIDOS</h3>
            <div className={styles.boxes}>
              <div className={styles.notBox}>
                <div className={styles.boxIconContainer}>
                  <LogoCorreoArgentinoIcon width={120} />
                </div>
                <p>
                  <span>Lorem Ipsum</span> dummy text oever since the 1500s, when an printer took a galley.
                </p>
              </div>
              <div className={styles.notBox}>
                <div className={styles.boxIconContainer}>
                  <LogoOcaIcon width={120} />
                </div>
                <p>
                  <span>Lorem Ipsum</span> dummy text oever since the 1500s, when an printer took a galley.
                </p>
              </div>
              <div className={styles.notBox}>
                <div className={styles.boxIconContainer}>
                  <LogoCorreoArgentinoIcon width={120} />
                </div>
                <p>
                  <span>Lorem Ipsum</span> dummy text ever since the 1500s, when an printer took a galley.
                </p>
              </div>
              <div className={styles.notBox}>
                <div className={styles.boxIconContainer}>
                  <LogoCorreoArgentinoIcon width={120} />
                </div>
                <p>
                  <span>Lorem Ipsum</span> dummy text ever since the 1500s, when an printer took a galley.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <ul className={styles.socialContainer}>
        <li>
          <Button className={'circleButton'} href="#">
            <FacebookIcon width="16" />
          </Button>
        </li>
        <li>
          <Button className={'circleButton'} href="#">
            <InstagramIcon width="16" />
          </Button>
        </li>
        <li>
          <Button className={'circleButton'} href="#">
            <YoutubeIcon width="16" />
          </Button>
        </li>
        <li>
          <Button className={'circleButton'} href="#">
            <WhatsappIcon width="16" />
          </Button>
        </li>
        <div className={styles.hr}></div>
      </ul>

      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <div className={styles.content}>
            <h2>HERRAMIENTAS RAPIDAS</h2>
            <ul>
              <li>
                <Link href="#">Seguimiento de envío</Link>
              </li>
              <li>
                <Link href="#">Lista de expresos</Link>
              </li>
              <li>
                <Link href="#">Tarifas y Pagos</Link>
              </li>
              <li>
                <Link href="#">Documentacion</Link>
              </li>
              <li>
                <Link href="#">Area Clientes</Link>
              </li>
              <li>
                <Link href="#">Códigos Postales Argentinos</Link>
              </li>
            </ul>
          </div>
          <div className={styles.content}>
            <h2>ACERCA DE</h2>
            <ul>
              <li>
                <Link href="#">SM LOGISTICA</Link>
              </li>
              <li>
                <Link href="#">Términos y condiciones</Link>
              </li>
              <li>
                <Link href="#">Política de privacidad</Link>
              </li>
            </ul>
            <h2>SERVICIOS</h2>
            <ul>
              <li>
                <Link href="#">Promociones</Link>
              </li>
              <li>
                <Link href="#">Tendencias</Link>
              </li>
              <li>
                <Link href="#">Envíos</Link>
              </li>
            </ul>
          </div>
          <div className={styles.content}>
            <h2>AYUDA</h2>
            <ul>
              <li>
                <Link href="#">¿Cómo enviar?</Link>
              </li>
              <li>
                <Link href="#">Condiciones de embalaje</Link>
              </li>
              <li>
                <Link href="#">Dónde veo mi número de guía</Link>
              </li>
              <li>
                <Link href="#">Preguntas generales</Link>
              </li>
              <li>
                <Link href="#">E-comerces</Link>
              </li>
              <li>
                <Link href="#">Pagos</Link>
              </li>
              <li>
                <Link href="#">Mi cuenta</Link>
              </li>
            </ul>
          </div>
          <div className={styles.content}>
            <h2>SUSCRIBITE A NUESTRO NEWSLETTER</h2>
            <h3>No te pierdas de toda la información nueva y promociones en SM LOGISTICA</h3>
            <form>
              <input placeholder="Introduce tu correo electronico" />
              <Button className={'formButton'} background={'var(--color-secundary-100)'}>
                SUSCRIBIRSE
              </Button>
            </form>
          </div>
        </div>
        <div className={styles.copyright}>&copy; 2022 SM LOGISTICA &middot; Todos los derechos reservados</div>
      </footer>
    </>
  )
}
